from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

ROUTING_LEXICON_FIELDS: tuple[str, ...] = (
    "memory_store_keywords",
    "memory_recall_keywords",
    "memory_store_prefixes",
    "memory_recall_cleanup_keywords",
    "memory_forget_keywords",
    "web_search_keywords",
    "web_search_prefixes",
    "web_search_cleanup_keywords",
    "skill_status_keywords",
    "skill_status_patterns",
    "skill_status_skill_terms",
    "skill_status_status_terms",
)

DEFAULT_ROUTING_LANGUAGE = "de"


@dataclass(frozen=True)
class CapabilityRoutingLexicon:
    write_terms: tuple[str, ...]
    read_terms: tuple[str, ...]
    feed_read_terms: tuple[str, ...]
    explicit_web_search_terms: tuple[str, ...]
    webhook_send_terms: tuple[str, ...]
    discord_send_terms: tuple[str, ...]
    api_terms: tuple[str, ...]
    api_action_terms: tuple[str, ...]
    email_send_terms: tuple[str, ...]
    email_send_action_terms: tuple[str, ...]
    mail_read_terms: tuple[str, ...]
    mail_search_terms: tuple[str, ...]
    mqtt_terms: tuple[str, ...]
    mqtt_action_terms: tuple[str, ...]
    ssh_command_terms: tuple[str, ...]
    webhook_action_terms: tuple[str, ...]
    discord_action_terms: tuple[str, ...]
    list_terms: tuple[str, ...]
    remote_terms: tuple[str, ...]
    ssh_hints: tuple[str, ...]
    sftp_hints: tuple[str, ...]
    smb_hints: tuple[str, ...]
    rss_hints: tuple[str, ...]
    webhook_hints: tuple[str, ...]
    discord_hints: tuple[str, ...]
    api_hints: tuple[str, ...]
    email_hints: tuple[str, ...]
    imap_hints: tuple[str, ...]
    mqtt_hints: tuple[str, ...]
    feed_subject_ignore_terms: tuple[str, ...]
    generic_connection_ref_tokens: tuple[str, ...]
    requested_connection_ref_ignore_terms: tuple[str, ...]
    discord_requested_ref_terms: tuple[str, ...]
    webhook_requested_ref_terms: tuple[str, ...]
    api_requested_ref_terms: tuple[str, ...]
    email_requested_ref_terms: tuple[str, ...]
    imap_requested_ref_terms: tuple[str, ...]
    mqtt_requested_ref_terms: tuple[str, ...]
    ssh_requested_ref_terms: tuple[str, ...]
    ssh_requested_ref_prepositions: tuple[str, ...]
    rss_requested_ref_terms: tuple[str, ...]
    ssh_natural_uptime_terms: tuple[str, ...]
    ssh_natural_online_terms: tuple[str, ...]
    mail_search_after_terms: tuple[str, ...]
    mqtt_topic_terms: tuple[str, ...]
    connection_kind_priority: tuple[str, ...]


_DEFAULT_ROUTING_LEXICONS: dict[str, dict[str, tuple[str, ...]]] = {
    "de": {
        "memory_store_keywords": ("merk", "speicher", "vergiss nicht", "notier"),
        "memory_recall_keywords": (
            "erinnerst",
            "weisst du noch",
            "weißt du noch",
            "was weisst du",
            "was weißt du",
            "letztes mal",
            "gespeichert",
            "was weisst du über",
            "was weißt du über",
        ),
        "memory_store_prefixes": (
            "merk dir, dass ",
            "merk dir dass ",
            "merk dir ",
            "speichere, dass ",
            "speichere dass ",
            "speichere ",
            "notier dir, dass ",
            "notier dir dass ",
            "notier dir ",
            "vergiss nicht, dass ",
            "vergiss nicht dass ",
            "vergiss nicht ",
        ),
        "memory_recall_cleanup_keywords": (
            "erinnerst du dich",
            "weisst du noch",
            "weißt du noch",
            "gespeichert",
            "letztes mal",
        ),
        "memory_forget_keywords": ("vergiss", "loesch", "lösch", "entfern", "delete", "remove"),
        "web_search_keywords": (
            "websuche",
            "suche im web",
            "suche in web",
            "recherchiere im web",
            "recherchiere in web",
            "such im web",
            "such in web",
            "suche im internet",
            "suche in internet",
            "recherchiere im internet",
            "recherchiere in internet",
            "such im internet",
            "such in internet",
            "internet suche",
            "internet search",
            "suche online",
            "recherchiere online",
            "search the web",
            "web search",
            "search web",
        ),
        "web_search_prefixes": (
            "websuche ",
            "suche im web ",
            "suche in web ",
            "recherchiere im web ",
            "recherchiere in web ",
            "such im web ",
            "such in web ",
            "suche im internet ",
            "suche in internet ",
            "recherchiere im internet ",
            "recherchiere in internet ",
            "such im internet ",
            "such in internet ",
            "suche online ",
            "recherchiere online ",
            "search the web ",
            "web search ",
            "search web ",
        ),
        "web_search_cleanup_keywords": ("im web", "in web", "online", "im internet", "in internet"),
        "skill_status_keywords": (
            "welche skills",
            "skills aktiv",
            "aktive skills",
            "aktuelle skills",
            "aktuellen skills",
            "installierte skills",
            "vorhandene skills",
            "deine skills",
            "deine fähigkeiten",
            "deine faehigkeiten",
            "skill status",
            "skills überprüfen",
            "skills ueberpruefen",
            "was kannst du aktuell ausführen",
            "was kannst du aktuell ausfuehren",
            "was kannst du ausführen",
            "was kannst du ausfuehren",
        ),
        "skill_status_patterns": (
            r"\bwas\s+f(?:ü|ue)r\s+skills\b",
            r"\bwas\s+sind\s+deine(?:r|n)?\s+.*skills\b",
            r"\bwelche\s+skills\b",
            r"\bskills?\s+hast\s+du\b",
            r"\bwelche\s+f(?:ä|ae)higkeiten\b",
            r"\bf(?:ä|ae)higkeiten\s+hast\s+du\b",
        ),
        "skill_status_skill_terms": ("skill", "skills", "fähigkeit", "fähigkeiten", "faehigkeit", "faehigkeiten"),
        "skill_status_status_terms": (
            "aktiv",
            "aktiviert",
            "status",
            "übersicht",
            "uebersicht",
            "überblick",
            "ueberblick",
            "liste",
            "enabled",
            "welche",
            "was für",
            "was fuer",
            "was sind",
            "hast du",
            "aktuell",
            "installiert",
            "vorhanden",
        ),
    },
    "en": {
        "memory_store_keywords": ("remember this", "remember that", "save this", "save that", "note this"),
        "memory_recall_keywords": (
            "do you remember",
            "what do you remember",
            "what do you know about",
            "last time",
            "saved",
        ),
        "memory_store_prefixes": (
            "remember this: ",
            "remember this ",
            "remember that ",
            "remember ",
            "save this: ",
            "save this ",
            "save that ",
            "save ",
            "note this: ",
            "note this ",
            "note that ",
            "note ",
        ),
        "memory_recall_cleanup_keywords": ("do you remember", "what do you remember", "saved", "last time"),
        "memory_forget_keywords": ("forget", "delete", "remove"),
        "web_search_keywords": (
            "search the web",
            "web search",
            "search web",
            "search the internet",
            "internet search",
            "search online",
            "research online",
            "look it up online",
            "look this up online",
            "look it up on the web",
        ),
        "web_search_prefixes": (
            "search the web ",
            "web search ",
            "search web ",
            "search the internet ",
            "internet search ",
            "search online ",
            "research online ",
            "look it up online ",
            "look this up online ",
            "look it up on the web ",
        ),
        "web_search_cleanup_keywords": ("online", "on the web", "on the internet"),
        "skill_status_keywords": (
            "skill status",
            "which skills",
            "what skills",
            "active skills",
            "current skills",
            "installed skills",
            "available skills",
            "your skills",
            "your capabilities",
            "what skills are active",
            "which skills are active",
            "what can you currently do",
            "what can you do right now",
        ),
        "skill_status_patterns": (
            r"\bwhich\s+skills\b",
            r"\bwhat\s+skills\b",
            r"\bwhat\s+skills\s+are\s+active\b",
            r"\bwhich\s+skills\s+are\s+active\b",
            r"\bwhat\s+skills\s+do\s+you\s+have\b",
            r"\bwhich\s+capabilities\b",
            r"\bwhat\s+capabilities\b",
            r"\bwhat\s+can\s+you\s+(?:currently\s+|right\s+now\s+)?do\b",
        ),
        "skill_status_skill_terms": ("skill", "skills", "capability", "capabilities"),
        "skill_status_status_terms": (
            "active",
            "enabled",
            "status",
            "overview",
            "list",
            "current",
            "installed",
            "available",
            "which",
            "what",
            "do you have",
            "can you do",
        ),
    },
}

_COMMON_CAPABILITY_TERMS: dict[str, tuple[str, ...]] = {
    "webhook_send_terms": (
        "webhook",
        "per webhook",
        "via webhook",
        "an webhook",
        "zum webhook",
        "an den webhook",
        "post an",
        "poste an",
        "schick an",
        "sende an",
        "sende per webhook",
        "schicke per webhook",
        "notify via webhook",
        "callback",
        "endpoint",
    ),
    "discord_send_terms": (
        "discord",
        "an discord",
        "nach discord",
        "zu discord",
        "per discord",
        "via discord",
        "in discord",
        "discord senden",
        "discord schicken",
        "discord nachricht",
        "send to discord",
        "send via discord",
        "discord message",
    ),
    "api_terms": ("api", "http api", "rest api", "endpoint", "rest endpoint"),
    "api_action_terms": (
        "ruf",
        "rufe",
        "call",
        "frage",
        "fetch",
        "hole",
        "hol",
        "zeige",
        "zeig",
        "get",
        "post",
        "put",
        "patch",
        "head",
        "sende",
        "send",
    ),
    "email_send_terms": (
        "mail",
        "email",
        "e-mail",
        "per mail",
        "per email",
        "via mail",
        "via email",
        "smtp",
    ),
    "email_send_action_terms": (
        "send",
        "sende",
        "schick",
        "schicke",
        "mail",
        "maile",
        "verschick",
        "verschicke",
    ),
    "mqtt_terms": ("mqtt", "broker", "topic", "publish", "iot"),
    "mqtt_action_terms": ("send", "sende", "schick", "schicke", "publish", "poste", "post"),
    "ssh_command_terms": (
        "run",
        "execute",
        "exec",
        "start",
        "starte",
        "führe",
        "fuehre",
        "uptime",
        "laufzeit",
        "betriebszeit",
        "wie lange läuft",
        "wie lange laeuft",
        "seit wann läuft",
        "seit wann laeuft",
        "healthcheck",
        "health check",
        "gesundheitscheck",
        "systemstatus",
        "command",
        "befehl",
    ),
    "webhook_action_terms": (
        "send",
        "sende",
        "schick",
        "schicke",
        "post",
        "poste",
        "melde",
        "alarmiere",
        "notify",
        "benachrichtige",
    ),
    "discord_action_terms": (
        "send",
        "sende",
        "schick",
        "schicke",
        "post",
        "poste",
        "melde",
        "alarmiere",
        "notify",
        "benachrichtige",
    ),
    "list_terms": (
        "liste",
        "liste mir",
        "list",
        "list files",
        "zeig dateien",
        "zeige dateien",
        "zeige mir die dateien",
        "was für dateien",
        "was fuer dateien",
        "welche dateien",
        "welche dateien liegen",
        "welche dateien gibt es",
        "was liegt in",
        "was ist in",
        "was liegt auf",
        "was ist auf",
        "was liegt in meinem share",
        "was ist in meinem share",
        "welche dateien liegen in",
        "inhalt von ordner",
        "inhalt vom ordner",
        "inhalt von verzeichnis",
        "ordner anzeigen",
        "ordnerinhalt",
        "verzeichnis",
        "daten aus",
        "daten im",
        "daten von",
        "zeige daten",
        "zeige mir daten",
        "zeige mir die daten",
        "inhalte von",
        "inhalt aus",
        "ordner von",
        "verzeichnis von",
        "directory",
        "files in",
        "ls ",
    ),
    "remote_terms": (
        "server",
        "remote",
        "host",
        "ssh",
        "sftp",
        "share",
        "freigabe",
        "nas",
        "netzlaufwerk",
        "smb",
        "ordner",
        "verzeichnis",
        "datei",
        "file",
        "/",
    ),
    "ssh_hints": ("ssh", "shell", "terminal", "server", "host", "linux", "linux-server"),
    "sftp_hints": ("sftp", "server", "host", "ssh", "linux-server"),
    "smb_hints": (
        "smb",
        "share",
        "freigabe",
        "nas",
        "netzlaufwerk",
        "windows-share",
        "synology",
        "volume",
        "docker share",
        "docker verzeichnis",
    ),
    "rss_hints": ("rss", "feed", "atom", "newsfeed", "news feed"),
    "webhook_hints": ("webhook", "hook", "callback", "endpoint"),
    "discord_hints": ("discord", "channel", "server", "webhook"),
    "api_hints": ("api", "rest", "endpoint", "http api"),
    "email_hints": ("mail", "email", "e-mail", "smtp"),
    "imap_hints": ("imap", "mailbox", "postfach", "inbox", "mail", "email", "e-mail"),
    "mqtt_hints": ("mqtt", "broker", "topic", "iot"),
    "feed_subject_ignore_terms": (
        "aktuell",
        "aktuelle",
        "auf",
        "aus",
        "bei",
        "das",
        "dem",
        "den",
        "der",
        "die",
        "eintraege",
        "entries",
        "es",
        "feed",
        "gibt",
        "gibts",
        "headlines",
        "im",
        "in",
        "ist",
        "latest",
        "meldungen",
        "mir",
        "neu",
        "neue",
        "neuen",
        "neues",
        "news",
        "online",
        "posts",
        "rss",
        "show",
        "tell",
        "the",
        "updates",
        "von",
        "was",
        "zeige",
        "zeig",
        "zu",
    ),
    "generic_connection_ref_tokens": (
        "api",
        "discord",
        "email",
        "feed",
        "hook",
        "http",
        "imap",
        "inbox",
        "mail",
        "mqtt",
        "news",
        "rss",
        "server",
        "share",
        "smtp",
        "sftp",
        "smb",
        "topic",
        "webhook",
    ),
    "requested_connection_ref_ignore_terms": (
        "a",
        "an",
        "about",
        "api",
        "broker",
        "channel",
        "dem",
        "den",
        "der",
        "discord",
        "email",
        "endpoint",
        "feed",
        "inbox",
        "kanal",
        "mail",
        "mailbox",
        "message",
        "messages",
        "mit",
        "mqtt",
        "my",
        "nachricht",
        "nachrichten",
        "postfach",
        "rss",
        "shell",
        "ssh",
        "topic",
        "the",
        "to",
        "ueber",
        "wegen",
        "webhook",
        "with",
        "zu",
        "über",
    ),
    "discord_requested_ref_terms": (
        "discord",
        "via discord",
    ),
    "webhook_requested_ref_terms": (
        "webhook",
        "via webhook",
        "per webhook",
    ),
    "api_requested_ref_terms": (
        "api",
        "endpoint",
    ),
    "email_requested_ref_terms": (
        "mail",
        "email",
    ),
    "imap_requested_ref_terms": (
        "postfach",
        "mailbox",
        "inbox",
    ),
    "mqtt_requested_ref_terms": (
        "mqtt",
        "broker",
    ),
    "ssh_requested_ref_terms": ("ssh",),
    "rss_requested_ref_terms": (
        "feed",
        "rss",
    ),
    "ssh_natural_uptime_terms": (
        "uptime",
        "laufzeit",
        "betriebszeit",
        "healthcheck",
        "health check",
        "gesundheitscheck",
        "systemstatus",
    ),
    "ssh_natural_online_terms": ("online",),
    "mail_search_after_terms": ("nach",),
    "mqtt_topic_terms": ("topic",),
    "connection_kind_priority": (
        "ssh",
        "sftp",
        "smb",
        "rss",
        "discord",
        "http_api",
        "webhook",
        "email",
        "imap",
        "mqtt",
    ),
}

_CAPABILITY_ROUTING_LEXICONS: dict[str, dict[str, tuple[str, ...]]] = {
    "de": {
        **_COMMON_CAPABILITY_TERMS,
        "write_terms": (
            "schreib",
            "schreibe",
            "erstell",
            "erstelle",
            "erzeuge",
            "lege an",
            "leg an",
            "aktualisier",
            "update file",
            "überschreib",
            "ueberschreib",
            "speicher als datei",
            "speichere als datei",
            "speicher in",
            "speichere in",
            "write",
            "create file",
            "save file",
            "write file",
            "save to",
        ),
        "read_terms": (
            "lies",
            "lese",
            "lies mir",
            "les mir",
            "zeig",
            "zeige",
            "zeig mir",
            "zeige mir",
            "zeige den inhalt",
            "gib mir den inhalt",
            "inhalt von",
            "öffne",
            "oeffne",
            "lade",
            "hol",
            "read",
            "show file",
            "open file",
            "read file",
            "cat ",
        ),
        "feed_read_terms": (
            "rss",
            "feed",
            "atom feed",
            "newsfeed",
            "news feed",
            "news",
            "nachrichten",
            "feed lesen",
            "feed anzeigen",
            "feed zeigen",
            "neueste einträge",
            "neueste meldungen",
            "was für news",
            "was fuer news",
            "was gibt es neues",
            "was gibts neues",
            "was gibs neues",
            "was ist neu",
            "gibts neues",
            "gibs neues",
            "headlines",
            "latest entries",
            "latest posts",
        ),
        "explicit_web_search_terms": (
            "websuche",
            "suche im web",
            "suche in web",
            "such im web",
            "such in web",
            "recherchiere im web",
            "recherchiere in web",
            "suche im internet",
            "suche in internet",
            "such im internet",
            "such in internet",
            "recherchiere im internet",
            "recherchiere in internet",
            "suche online",
            "recherchiere online",
            "search the web",
            "web search",
            "search web",
            "internet search",
        ),
        "mail_read_terms": (
            "mails lesen",
            "mail lesen",
            "emails lesen",
            "email lesen",
            "zeige mails",
            "zeige emails",
            "neueste mails",
            "neueste emails",
            "ungelesene mails",
            "ungelesene emails",
            "inbox",
            "mailbox",
            "postfach",
        ),
        "mail_search_terms": (
            "suche mails",
            "suche emails",
            "finde mails",
            "finde emails",
            "durchsuche mailbox",
            "durchsuche postfach",
            "search mails",
            "search emails",
        ),
        "requested_connection_ref_ignore_terms": (
            *_COMMON_CAPABILITY_TERMS["requested_connection_ref_ignore_terms"],
            "das",
            "ein",
            "eine",
            "einem",
            "einen",
            "mein",
            "meinem",
            "meinen",
        ),
        "discord_requested_ref_terms": (
            *_COMMON_CAPABILITY_TERMS["discord_requested_ref_terms"],
            "nach discord",
            "zu discord",
            "an discord",
        ),
        "email_requested_ref_terms": (
            *_COMMON_CAPABILITY_TERMS["email_requested_ref_terms"],
            "mail an",
            "email an",
            "mail an den",
            "email an den",
            "per mail",
            "per email",
            "via mail",
            "via email",
        ),
        "ssh_requested_ref_prepositions": ("auf", "bei", "via", "von"),
        "ssh_natural_uptime_terms": (
            *_COMMON_CAPABILITY_TERMS["ssh_natural_uptime_terms"],
            "wie lange läuft",
            "wie lange laeuft",
            "seit wann läuft",
            "seit wann laeuft",
        ),
        "ssh_natural_online_terms": (
            *_COMMON_CAPABILITY_TERMS["ssh_natural_online_terms"],
            "wie lange ist",
            "seit wann ist",
        ),
        "mail_search_after_terms": (
            *_COMMON_CAPABILITY_TERMS["mail_search_after_terms"],
            "betreff",
        ),
        "mqtt_topic_terms": (
            *_COMMON_CAPABILITY_TERMS["mqtt_topic_terms"],
            "auf topic",
            "an topic",
        ),
    },
    "en": {
        **_COMMON_CAPABILITY_TERMS,
        "write_terms": (
            "write",
            "write file",
            "create file",
            "create",
            "save file",
            "save to",
            "overwrite",
            "update file",
            "store in file",
        ),
        "read_terms": (
            "read",
            "read file",
            "show file",
            "show me",
            "show me the contents",
            "show contents",
            "contents of",
            "open",
            "open file",
            "load",
            "get",
            "cat ",
        ),
        "feed_read_terms": (
            "rss",
            "feed",
            "atom feed",
            "newsfeed",
            "news feed",
            "news",
            "read feed",
            "show feed",
            "latest entries",
            "latest posts",
            "latest headlines",
            "what's new",
            "whats new",
            "what is new",
            "headlines",
        ),
        "explicit_web_search_terms": (
            "search the web",
            "web search",
            "search web",
            "internet search",
            "search the internet",
            "search online",
            "research online",
            "look it up online",
            "look it up on the web",
        ),
        "mail_read_terms": (
            "read mail",
            "read emails",
            "read email",
            "show mails",
            "show emails",
            "latest mails",
            "latest emails",
            "unread mails",
            "unread emails",
            "inbox",
            "mailbox",
        ),
        "mail_search_terms": (
            "search mails",
            "search emails",
            "find mails",
            "find emails",
            "search mailbox",
            "search inbox",
        ),
        "requested_connection_ref_ignore_terms": (
            *_COMMON_CAPABILITY_TERMS["requested_connection_ref_ignore_terms"],
            "me",
        ),
        "discord_requested_ref_terms": (
            *_COMMON_CAPABILITY_TERMS["discord_requested_ref_terms"],
            "to discord",
        ),
        "email_requested_ref_terms": (
            *_COMMON_CAPABILITY_TERMS["email_requested_ref_terms"],
            "mail to",
            "email to",
            "via mail",
            "via email",
        ),
        "ssh_requested_ref_prepositions": ("on", "via", "from"),
        "ssh_natural_uptime_terms": (
            *_COMMON_CAPABILITY_TERMS["ssh_natural_uptime_terms"],
            "how long",
        ),
        "ssh_natural_online_terms": (
            *_COMMON_CAPABILITY_TERMS["ssh_natural_online_terms"],
            "been online",
            "how long is",
        ),
        "mail_search_after_terms": (
            *_COMMON_CAPABILITY_TERMS["mail_search_after_terms"],
            "for",
            "subject",
        ),
        "mqtt_topic_terms": (
            *_COMMON_CAPABILITY_TERMS["mqtt_topic_terms"],
            "on topic",
        ),
    },
}


def _dedupe_preserving_order(values: Iterable[str]) -> list[str]:
    rows: list[str] = []
    seen: set[str] = set()
    for value in values:
        text = str(value)
        if not text or text in seen:
            continue
        seen.add(text)
        rows.append(text)
    return rows


def _dedupe_tuple_preserving_order(values: Iterable[str]) -> tuple[str, ...]:
    return tuple(_dedupe_preserving_order(values))


def get_default_routing_profile(language: str | None = None) -> dict[str, list[str]]:
    lang_key = str(language or DEFAULT_ROUTING_LANGUAGE).strip().lower() or DEFAULT_ROUTING_LANGUAGE
    raw = _DEFAULT_ROUTING_LEXICONS.get(lang_key, _DEFAULT_ROUTING_LEXICONS[DEFAULT_ROUTING_LANGUAGE])
    return {
        field_name: _dedupe_preserving_order(raw.get(field_name, ()))
        for field_name in ROUTING_LEXICON_FIELDS
    }


def get_default_routing_languages() -> dict[str, dict[str, list[str]]]:
    return {
        language: get_default_routing_profile(language)
        for language in _DEFAULT_ROUTING_LEXICONS
        if language != DEFAULT_ROUTING_LANGUAGE
    }


def get_default_capability_lexicon(language: str | None = None) -> CapabilityRoutingLexicon:
    lang_key = str(language or DEFAULT_ROUTING_LANGUAGE).strip().lower() or DEFAULT_ROUTING_LANGUAGE
    raw = _CAPABILITY_ROUTING_LEXICONS.get(lang_key, _CAPABILITY_ROUTING_LEXICONS[DEFAULT_ROUTING_LANGUAGE])
    return CapabilityRoutingLexicon(
        **{
            field_name: _dedupe_tuple_preserving_order(raw.get(field_name, ()))
            for field_name in CapabilityRoutingLexicon.__dataclass_fields__
        }
    )
