"""Declarative metadata for the existing Pipeline orchestrator."""

from __future__ import annotations

from typing import Any


MODULE_MANIFEST: dict[str, Any] = {
    "id": "pipeline_orchestrator",
    "name": "Pipeline Orchestrator",
    "parent": "actions",
    "status": "implementation_owner_active",
    "lifecycle": "bootstrap_static",
    "risk": "high_core",
    "description": "Owns complete Pipeline composition, including loading enabled Recipe manifests before the sole MetaCatalog turn decision and delegating validated results.",
    "python": [
        "aria/modules/pipeline_orchestrator/pipeline.py",
        "aria/modules/pipeline_orchestrator/agent_jobs.py",
    ],
    "tests": [
        "tests/test_pipeline.py",
        "tests/test_async_agent_jobs.py",
        "tests/test_authority_chain_audit.py",
        "tests/test_pipeline_orchestrator_ownership_import_boundary.py",
        "tests/test_module_registry.py",
    ],
    "depends_on": [
        "action_contracts",
        "action_planner_templates",
        "action_runtime_debug",
        "agentic_prompt_flow",
        "agentic_stabilization",
        "capability_context",
        "capability_error_messages",
        "capability_runtime",
        "configuration_foundations",
        "connection_routing",
        "connections_catalog",
        "connections_semantic",
        "execution_dry_run",
        "execution_dry_run_payloads",
        "http_api_policy",
        "integration_support",
        "llm_input_contract",
        "model_gateway_clients",
        "model_usage_observability",
        "operator_trace_boundary",
        "pipeline_capability_execution",
        "pipeline_contracts",
        "pipeline_pending_action_contracts",
        "platform_primitives",
        "recipe_runtime",
        "rss_digest",
        "rss_runtime",
        "runtime_execution_registry",
        "ssh_policy",
        "ssh_runtime",
        "system_inventory",
        "memory_learning_bridge",
        "qdrant_gateway",
        "skill_contracts",
        "memory",
    ],
    "external_boundaries": [],
    "explicitly_excluded": [
        "pipeline_method_split_rewrite",
        "websearch_memory_or_non_recipe_source_authority_changes",
        "target_fleet_planner_confirmation_or_guardrail_changes",
        "runtime_handler_registration_execution_or_result_changes",
        "memory_recipe_learning_or_persistence_changes",
        "non_recipe_call_count_timeout_retry_or_latency_changes",
        "productive_qdrant_connection_secret_or_user_data_access",
    ],
    "acceptance": ".codex/aria_acceptance/recipe-live-route-source-preview-alpha792.json",
    "build_allowed": False,
    "runtime_access_allowed": False,
    "notes": [
        "The historical aria.core path and canonical path share one module and Pipeline class identity.",
        "Moved relative paths continue to resolve aria/i18n and the repository root.",
        "Recipe manifests are loaded once per turn and reach MetaCatalog before any Recipe presentation or execution handoff.",
    ],
}
