"""Declarative metadata for the config UI module."""

from __future__ import annotations

from typing import Any


MODULE_MANIFEST: dict[str, Any] = {
    "id": "config_ui",
    "name": "Config UI",
    "status": "composition_owner_active",
    "lifecycle": "bootstrap_static",
    "risk": "medium_needs_proof",
    "description": "Owns settings/config pages until connection, routing, backup, and diagnostics pages are split to narrower modules.",
    "routes_prefixes": [
        "/config",
    ],
    "routes": [
        "/config",
        "/config/admin/modules",
        "/config/admin/ui-audit",
        "/config/admin/ui-audit/save",
        "/config/admin/ui-audit/save-all",
        "/config/admin/ui-audit/export",
        "/config/access",
        "/config/admin-mode",
        "/config/security",
        "/config/security/guardrails/draft",
        "/config/security/guardrails/save",
        "/config/security/guardrails/test",
        "/config/security/guardrails/delete",
        "/config/security/guardrails/import-sample",
        "/config/users",
        "/config/users/security-save",
        "/config/users/create",
        "/config/users/update",
        "/config/intelligence",
        "/config/persona",
        "/config/routing-index/status",
        "/config/routing-index/test",
        "/config/llm",
        "/config/embeddings",
        "/config/prompts",
        "/config/appearance",
        "/config/language",
        "/config/files",
        "/config/files/save",
        "/config/error-interpreter",
        "/config/llm/debug",
        "/config/admin-mode/save",
        "/config/appearance/save",
        "/config/language/save",
        "/config/language/file/save",
        "/config/prompts/save",
        "/config/error-interpreter/save",
        "/config/llm/debug/clear",
        "/config/llm/models",
        "/config/llm/test",
        "/config/llm/roles",
        "/config/llm/web/test",
        "/config/llm/profile/load",
        "/config/llm/profile/delete",
        "/config/llm/save",
        "/config/llm/profile/save",
        "/config/embeddings/test",
        "/config/embeddings/profile/load",
        "/config/embeddings/profile/delete",
        "/config/embeddings/models",
        "/config/embeddings/save",
        "/config/embeddings/profile/save",
        "/config/connections/mcp",
        "/config/connections/mcp/save",
        "/config/connections/mcp/master",
        "/config/connections/mcp/reconnect",
        "/config/connections/mcp/delete",
    ],
    "python": [
        "aria/modules/config_ui/links.py",
        "aria/modules/config_ui/routes.py",
        "aria/modules/config_ui/misc_helpers.py",
        "aria/modules/config_ui/profile_helpers.py",
        "aria/modules/config_ui/support_helpers.py",
        "aria/modules/config_ui/surface_helpers.py",
        "aria/modules/config_ui/surface_routes.py",
        "aria/modules/config_ui/ui_audit.py",
        "aria/modules/config_ui/access_detail_routes.py",
        "aria/modules/config_ui/intelligence_workbench_routes.py",
        "aria/modules/config_ui/persona_routes.py",
        "aria/modules/config_ui/routing_index_routes.py",
        "aria/modules/config_ui/main_helpers.py",
        "aria/modules/config_ui/mcp_server_routes.py",
    ],
    "templates": [
        "config.html",
        "config_access.html",
        "config_admin_mode.html",
        "config_admin_modules.html",
        "config_admin_ui_audit.html",
        "config_appearance.html",
        "config_embeddings.html",
        "config_error_interpreter.html",
        "config_files.html",
        "config_hub.html",
        "config_intelligence.html",
        "config_language.html",
        "config_llm.html",
        "config_llm_debug.html",
        "config_persona.html",
        "config_prompts.html",
        "config_connections_mcp.html",
        "config_security.html",
        "config_users.html",
        "_config_access_section.html",
        "_config_admin_notice.html",
        "_config_intelligence_section.html",
        "_config_nav.html",
        "_config_operations_section.html",
        "_config_page_header.html",
        "_config_persona_section.html",
    ],
    "tests": [
        "tests/test_config_routes.py",
        "tests/test_config_env_overrides.py",
        "tests/test_main_config_cache.py",
    ],
    "depends_on": [
        "auth_ui",
        "configuration_foundations",
        "navigation_shell",
        "mcp",
        "runtime_diagnostics",
    ],
    "external_boundaries": [
        {
            "id": "kernel.templates",
            "category": "kernel_platform",
            "disposition": "durable",
        },
    ],
    "explicitly_excluded": [
        "legacy_connection_profile_mutation",
        "routing_semantics",
        "config_backup",
        "runtime_diagnostics",
        "release_update",
        "memory_runtime",
    ],
    "acceptance": ".codex/aria_acceptance/config-ui-composition-ownership-rail-alpha745.json",
    "build_allowed": False,
    "runtime_access_allowed": False,
    "notes": [
        "This module still needs smaller splits before behavior moves.",
        "Connection config pages overlap with connections.",
        "Routing config pages overlap with routing.",
        "Operations pages overlap with ops_config_backup.",
    ],
}
