"""Declarative metadata for static help/docs surfaces."""

from __future__ import annotations

from typing import Any


MODULE_MANIFEST: dict[str, Any] = {
    "id": "static_help_docs",
    "name": "Static Help Docs",
    "status": "import_boundary_active",
    "lifecycle": "bootstrap_static",
    "risk": "low_medium",
    "description": "Owns read-only help, license, product-info docs surfaces and their markdown/wiki source files.",
    "routes": [
        "/help",
        "/licenses",
        "/product-info",
        "/product-info/assets/{asset_name}",
    ],
    "python": [
        "aria/modules/static_help_docs/routes.py",
    ],
    "templates": [
        "help.html",
        "licenses.html",
        "product_info.html",
    ],
    "docs": [
        "docs/help/",
        "docs/wiki/",
    ],
    "help_doc_groups": [
        {
            "id": "wiki",
            "label_i18n": "help.group_wiki",
            "label_default": "Wiki & Guides",
        },
        {
            "id": "reference",
            "label_i18n": "help.group_reference",
            "label_default": "Technical reference",
        },
    ],
    "help_docs": [
        {
            "id": "home",
            "label_i18n": "help.doc_home",
            "label_default": "Wiki Home",
            "path": "docs/wiki/Home.md",
            "summary_i18n": "help.doc_home_summary",
            "summary_default": "Starting point for orientation, documentation paths, and recommended first steps.",
            "icon": "help",
            "group": "wiki",
        },
        {
            "id": "quick-start",
            "label_i18n": "help.doc_quick_start",
            "label_default": "Quick Start",
            "path": "docs/wiki/Quick-Start.md",
            "summary_i18n": "help.doc_quick_start_summary",
            "summary_default": "Fast path from Docker or Portainer to the first usable ARIA instance.",
            "icon": "updates",
            "group": "wiki",
        },
        {
            "id": "chat",
            "label_i18n": "help.doc_chat",
            "label_default": "Chat & Queue",
            "path": "docs/help/chat.md",
            "summary_i18n": "help.doc_chat_summary",
            "summary_default": "How chat, prompt queue, confirmations, details, and mobile use work.",
            "icon": "llm",
            "group": "wiki",
        },
        {
            "id": "navigation",
            "label_i18n": "help.doc_navigation",
            "label_default": "Navigation & Menus",
            "path": "docs/help/navigation.md",
            "summary_i18n": "help.doc_navigation_summary",
            "summary_default": "How header navigation, the account menu, Settings, Admin, and Extended view fit together.",
            "icon": "settings",
            "group": "wiki",
        },
        {
            "id": "memory",
            "label_i18n": "help.doc_memory",
            "label_default": "Memory",
            "path": "docs/wiki/Memory.md",
            "summary_i18n": "help.doc_memory_summary",
            "summary_default": "Memory, RAG documents, the graphical Memory browser, and recall behavior explained compactly.",
            "icon": "memories",
            "group": "wiki",
        },
        {
            "id": "notes",
            "label_i18n": "help.doc_notes",
            "label_default": "Notes",
            "path": "docs/help/notes.md",
            "summary_i18n": "help.doc_notes_summary",
            "summary_default": "Markdown notes, folders, moving notes, list view, bulk move, and indexing.",
            "icon": "notes",
            "group": "wiki",
        },
        {
            "id": "skills",
            "label_i18n": "help.doc_skills",
            "label_default": "Recipes",
            "path": "docs/wiki/Recipes.md",
            "summary_i18n": "help.doc_skills_summary",
            "summary_default": "How recipes are structured, how triggers work, and how ARIA executes them.",
            "icon": "skills",
            "group": "wiki",
        },
        {
            "id": "agentic",
            "label_i18n": "help.doc_agentic",
            "label_default": "Agentic Operator",
            "path": "docs/help/agentic-operator.md",
            "summary_i18n": "help.doc_agentic_summary",
            "summary_default": "The controlled operator flow: understanding, context, policy, runtime, result, and learning.",
            "icon": "routing",
            "group": "wiki",
        },
        {
            "id": "connections",
            "label_i18n": "help.doc_connections",
            "label_default": "Connections",
            "path": "docs/wiki/Connections.md",
            "summary_i18n": "help.doc_connections_summary",
            "summary_default": "Overview of connection types, configuration, and routing value.",
            "icon": "settings",
            "group": "wiki",
        },
        {
            "id": "releases",
            "label_i18n": "help.doc_releases",
            "label_default": "Releases & Upgrades",
            "path": "docs/wiki/Releases-and-Upgrades.md",
            "summary_i18n": "help.doc_releases_summary",
            "summary_default": "How releases, local TAR updates, and upgrade flows fit together.",
            "icon": "updates",
            "group": "wiki",
        },
        {
            "id": "pricing",
            "label_i18n": "help.doc_pricing",
            "label_default": "Pricing",
            "path": "docs/help/pricing.md",
            "summary_i18n": "help.doc_pricing_summary",
            "summary_default": "How ARIA resolves prices for LLM and embedding models and calculates costs.",
            "icon": "stats",
            "group": "reference",
        },
        {
            "id": "qdrant",
            "label_i18n": "help.doc_qdrant",
            "label_default": "Qdrant",
            "path": "docs/help/qdrant.md",
            "summary_i18n": "help.doc_qdrant_summary",
            "summary_default": "What ARIA uses Qdrant for, what gets stored there, and what matters in day-to-day operation.",
            "icon": "memories",
            "group": "reference",
        },
        {
            "id": "security",
            "label_i18n": "help.doc_security",
            "label_default": "Security",
            "path": "docs/help/security.md",
            "summary_i18n": "help.doc_security_summary",
            "summary_default": "Session-, Guardrail- und Sicherheitsprinzipien der aktuellen ALPHA-Linie.",
            "icon": "security",
            "group": "reference",
        },
        {
            "id": "alpha-help-system",
            "label_i18n": "help.doc_alpha_help_system",
            "label_default": "Alpha Help System",
            "path": "docs/wiki/Alpha-Help-System.md",
            "summary_i18n": "help.doc_alpha_help_system_summary",
            "summary_default": "Full practical alpha help covering chat, memory, connections, recipes, costs, updates, and security.",
            "icon": "help",
            "group": "reference",
        },
        {
            "id": "help-system",
            "label_i18n": "help.doc_help_system",
            "label_default": "Help System",
            "path": "docs/wiki/Help-System.md",
            "summary_i18n": "help.doc_help_system_summary",
            "summary_default": "Documentation maintenance notes for keeping local help and wiki content aligned.",
            "icon": "files",
            "group": "reference",
        },
    ],
    "product_docs": [
        {
            "id": "overview",
            "label_i18n": "product_info.doc_overview",
            "label_default": "Product overview",
            "path": "docs/product/overview.md",
            "summary_i18n": "product_info.doc_overview_summary",
            "summary_default": "What ARIA is, who it is for, and where the current ALPHA boundary is.",
            "icon": "product",
            "assets": (),
        },
        {
            "id": "feature-list",
            "label_i18n": "product_info.doc_feature_list",
            "label_default": "Feature-Liste",
            "path": "docs/product/feature-list.md",
            "summary_i18n": "product_info.doc_feature_list_summary",
            "summary_default": "Technical feature snapshot for chat, memory, recipes, connections, UI, and deployment.",
            "icon": "skills",
            "assets": (),
        },
        {
            "id": "architecture",
            "label_i18n": "product_info.doc_architecture",
            "label_default": "Architecture",
            "path": "docs/product/architecture-summary.md",
            "summary_i18n": "product_info.doc_architecture_summary",
            "summary_default": "Layer model, routing, recipes, persistence, security, and update strategy.",
            "icon": "routing",
            "assets": (
                {
                    "src": "/product-info/assets/aria_schichten_architektur.svg",
                    "caption_i18n": "product_info.diagram_layers",
                    "caption_default": "Layer architecture",
                },
                {
                    "src": "/product-info/assets/aria_intelligentes_routing.svg",
                    "caption_i18n": "product_info.diagram_routing",
                    "caption_default": "Routing-Fluss",
                },
                {
                    "src": "/product-info/assets/aria_modularitaet_persistenz.svg",
                    "caption_i18n": "product_info.diagram_persistence",
                    "caption_default": "Modularity and persistence",
                },
            ),
        },
    ],
    "product_info_assets": {
        "aria_schichten_architektur.svg": "docs/product/aria_schichten_architektur.svg",
        "aria_intelligentes_routing.svg": "docs/product/aria_intelligentes_routing.svg",
        "aria_modularitaet_persistenz.svg": "docs/product/aria_modularitaet_persistenz.svg",
    },
    "file_editor_entries": [
        {
            "id": "memory_help",
            "path": "docs/help/memory.md",
            "label": "Memory Help",
            "group": "help",
            "mode": "readonly",
        },
        {
            "id": "pricing_help",
            "path": "docs/help/pricing.md",
            "label": "Pricing Help",
            "group": "help",
            "mode": "readonly",
        },
        {
            "id": "security_help",
            "path": "docs/help/security.md",
            "label": "Security Help",
            "group": "help",
            "mode": "readonly",
        },
    ],
    "tests": [
        "tests/test_help_page.py",
        "tests/test_module_registry.py",
    ],
    "depends_on": [
        "navigation_shell",
        "platform_primitives",
    ],
    "external_boundaries": [
        {
            "id": "kernel.templates",
            "category": "kernel_platform",
            "disposition": "durable",
        },
    ],
    "explicitly_excluded": [
        "docs_content_rewrite",
        "markdown_renderer_behavior",
        "runtime_actions",
        "web_search",
        "memory",
        "routing",
    ],
    "acceptance": ".codex/aria_acceptance/web-ui-composition-ownership-rail-alpha744.json",
    "build_allowed": False,
    "runtime_access_allowed": False,
    "notes": [
        "Static Help Docs route implementation is canonical in aria.modules.static_help_docs; the historical aria.web path is an identity alias.",
        "Route registration remains explicit in aria.main and is not generated from this manifest.",
    ],
}
